# Generated by Django 5.1.4 on 2025-02-11 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools_and_trainings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='certifier',
            field=models.ForeignKey(default=801276949, on_delete=django.db.models.deletion.DO_NOTHING, related_name='given_trainings', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
