# Generated by Django 5.1.4 on 2025-03-10 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools_and_trainings', '0002_training_certifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='training_level',
            field=models.IntegerField(choices=[(0, 'Apprentice'), (30, 'Operator'), (70, 'Trainer'), (100, 'Certifier')], default=0),
        ),
    ]
