# Generated by Django 5.1.4 on 2025-04-08 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association_tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
