# Generated by Django 5.1.4 on 2024-12-19 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpaceUser',
            fields=[
                ('niner_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.TextField(blank=True)),
                ('last_name', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('canvas_id', models.IntegerField(blank=True)),
            ],
        ),
    ]
