# Generated by Django 5.1.4 on 2025-01-13 23:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_spaceuser_groups_spaceuser_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_keyholder', models.BooleanField()),
                ('is_prefered_keyholder', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyholder', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KeyholderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('keyholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyholder_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
