# Generated by Django 5.1.4 on 2025-01-14 00:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_keyholder_keyholderhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='spaceuser',
            name='user_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
    ]
