# Generated by Django 5.1.4 on 2025-01-17 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_keyholder_is_prefered_keyholder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyholder',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='keyholder', to=settings.AUTH_USER_MODEL),
        ),
    ]
