name: Django Tests with Docker Compose

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Compose
      run: |
        docker compose -f docker-compose.yaml up -d

    - name: Run Django tests
      run: |
        docker compose exec -T web python manage.py test

    - name: Tear down Docker Compose
      run: |
        docker compose down
